/******************************************
*******************************************   
**                                       **
**    ------- SORTEO EL KINO -------     **
**                                       **
**   User:  DevelTwist                   **
**                                       **
**   Realizado:  20/10/2016              **
**                                       **
**   Ultima Actualizacion: 11/11/2016    **
**                                       **
**                                       **
*******************************************
******************************************/


/*El KINO es un juego tradicional de lotería, que consiste en un ticket, formado por 15 números aleatorios, ordenados.
Los números pertenecen al conjunto [1,25]. Se generan N tickets, y se realiza un sorteo.
son tickets ganadores, los que acierten 12, 13,14 y 15 números. */

/* The KINO is a traditional lottery game, Which Consist of a ticket Consisting of 15 random numbers, ordered.
The numbers belong to the set [1.25]. X tickets are generated, and a draw is made.
tickets are winners, Those Who match 12 numbers 13,14 and 15. */

/* Nota: En Mi Caso Coloco de 2 a 10 Cartones para limitar el numero de entrada.
pero no necesariamente tiene que pasar esto. son N Tickets generados por el usuario. */ 

/*	Note: In my case I place 2 to 10 Tickets to limit the number of entry.
But  Not Necessarily Have to happen. are N inputs generated by the user. */

// This is my first project for the community github. //
// Este es mi primer proyecto para la comunidad de github //


#include <stdio.h>
#include <stdlib.h>
#include <windows.h>
#include <conio.h>
#include <math.h>
#include <time.h>
#include <string.h>
#include "conio.h"
#define N_CARTON 15
#define N_SORTEO 25


int Validar_Numero(int n);
void Generar_Ticket(int Ticket[]);
int NumeroRandomNoRepetido(int Ticket[],int Espacios, int min, int max);
int Random(int min, int max);
int Repetido(int Ticket[],int valor,int Espacios);
void Imprimir_Ticket(int jugador[],int Bolitas[]);
void Ordenar_Vector(int a[]);
void Generar_Bolita(int Bolitas[]);
void Mostrar_Numero(int Bolitas[]);
int Comparar_Ganador(int Ticket[],int Bolitas[]);
void pintar(int Bolitas2[],int jugador[],int i);


int main(){

	int Ticket[N_CARTON];
	int jugador[10][2];
	int Bandera[N_CARTON];
	int n,cartones,serial=8520;
	int i,m,l;
	int Bolitas[25];
	char r;
	int prueba[25];
	int resultado;
	int perdedor,ganador;
	srand(time(NULL));

	do{
		
		perdedor = 0;
		ganador = 0;
	
	do{
		system("cls");
		printf ("Introduce Un Numero Entero [2-10]: ");
		scanf ("%d",&n);
		cartones = n;
	}while(Validar_Numero(n) == 1);


	for(i = 0 ; i < 25 ; i++){
		Bolitas[i] = 0;
	}


	printf ("Se Generara el Sorteo Con %d Cartones Desea Continuar? (S/N): ",n);
	fflush(stdin);
	scanf ("%c",&r);
	
	if(r == 'n' || r == 'N'){
		break;
	}
	
	for (i = 0 ; i < 15 ; i++){
		system("cls");
		Generar_Bolita(Bolitas);
		Mostrar_Numero(Bolitas);
		Sleep(200);
	}
	
	printf("\n\n\t\t\t\tCARTONES\n\n");

	for(i = 0 ; i < n ; i++){
		serial++;
		printf("\n--------------------------------------------------------------------\n");
		printf("\n\nSERIAL NUMERO: %d: \n",serial);
		printf("\n");
		Generar_Ticket(Ticket);
		Ordenar_Vector(Ticket);
		Imprimir_Ticket(Ticket,Bolitas);
		resultado = Comparar_Ganador(Ticket,Bolitas);
		if(resultado >= 12){
			ganador++;
			printf ("\n\n NUMERO DE ACIERTOS: %d. \n\n",resultado);
			printf ("\n\nBOLETO GANADOR.!!! \n\n");
		}
		else{
			perdedor++;
			printf ("\n NUMERO DE ACIERTOS: %d. \n",resultado);
			printf ("\n\nBOLETO NO GANADOR. LO SIENTO \n\n");
		}
		printf("\n--------------------------------------------------------------------\n");
		Sleep(400);
	}
		
		if(ganador > 0){
			printf ("\n\n\t HUBO: %d Ganadores En Este Sorteo. \t\n\n",ganador);
		}
		else if(perdedor = 15){
			printf ("\n\n\t NO HUBO GANADOR EN ESTE SORTEO \t\n\n");
		}
	

		printf ("\n\n Quieres Generar Un Nuevo Sorteo? (S/N): ");
		fflush(stdin);
		scanf("%c",&r);	
		
	}while(r == 's' || r == 'S');

	system ("cls");
	printf ("\n\n\t GRACIAS POR USAR EL PROGRAMA. !!!\t\n\n");

	printf ("\n\n");
	system ("pause");
	return 0;
}

int Comparar_Ganador(int Ticket[],int Bolitas[]){ // Compara el ganador sin el uso de un vector paralelo.
	
	int i,j,cont;
	int Bolitas2[15];
	
	cont = 0;
	for(i = 0 ; i < 25 ; i++){
		if(Bolitas[i]!=0){
			Bolitas2[cont] = Bolitas[i];
			cont+=1;
		}
	}
	
	cont = 0;
    for(i=0 ; i < 15 ; i++){
        for(j=0; j < 15 ; j++){
        	if(Ticket[i] == Bolitas2[j]){
            	Bolitas2[j]=0;
            	cont+=1;
        	}
		}
    }
    
    return cont;	
}

void Generar_Bolita(int Bolitas[]){ // Genera un Numero aleatorio para comparar con los cartones.

	int aleatorio = NumeroRandomNoRepetido(Bolitas,N_SORTEO,1,N_SORTEO);

	Bolitas[aleatorio-1]=aleatorio;

}

void Mostrar_Numero(int Bolitas[]){ // Imprime Las Bolitas 
    int i;  

    printf("Bolitas Del Kino: \n");
    for (i = 0; i < N_SORTEO ; i++) {
       
        if(Bolitas[i]!=0){
            printf ("%.2d\t", Bolitas[i]);
        }
    }
    printf ("\n");
}

int Validar_Numero(int n){ // Validar que el Numero de entrada este entre 2 y 10.

	if(n<2 || n>10){
		return 1;
	}

}

void Generar_Ticket(int Ticket[]){ // Genera un Ticket Con Numeros Aleatorios no repetidos.

	int i;


	for(i = 0 ; i < N_CARTON ; i++){
		Ticket[i] = NumeroRandomNoRepetido(Ticket,N_CARTON,1,N_SORTEO);
	}


}

int NumeroRandomNoRepetido(int Ticket[],int Espacios, int min, int max){ // Genera un Numero Aleatorio no Repetido...

	int i , aleatorio;

	do{
		aleatorio = Random(min,max);
	}while(Repetido(Ticket,aleatorio,Espacios));

	return aleatorio;
}

int Random(int min, int max) { // Numeros aleatorios entre 1 y 25.
    int numero;

    numero = (rand() % (max - min + 1)) + min;

    return numero;
}

int Repetido(int Ticket[],int valor,int Espacios){ // Comprobar si esta repetido.

    int i;
    for(i=0 ; i< Espacios ; i++){
        if(Ticket[i] == valor){
            return 1;
            break;
        }
    }
    return 0;
}

void Imprimir_Ticket(int jugador[],int Bolitas[]){ // Imprimir el Ticket.

	int i,j,cont;
	int aux;
	int Bolitas2[15];
	
	cont = 0;
	for(i = 0 ; i < 25 ; i++){
		if(Bolitas[i]!=0){
			Bolitas2[cont] = Bolitas[i];
			cont+=1;
		}
	}
	
	cont = 0;

	for(i = 0 ; i < N_CARTON ; i++){
		pintar(Bolitas2,jugador,i);
		printf("  %.2d",jugador[i]);
		textcolor(15);
		if((i+1)%3==0){
			printf("\n");
		}
	}

}

void pintar(int Bolitas2[],int jugador[],int i){
	
	int j;
		
	for (j = 0 ; j < 15 ; j++){
		if(Bolitas2[j] == jugador[i]){
			textcolor(10);
			break;
		}   
	}
	
}

void Ordenar_Vector(int a[]){ // Ordenar de Menor a mayor los valores del Ticket.

	int aux,i,j;
	int n = 15;

	aux = 0;
	for(i = 0 ; i < n ; i++){
		for(j = 0 ; j < n ; j++){
			if(a[i]<a[j]){
				aux = a[i];
				a[i]= a[j];
				a[j]= aux;
			}
		}
	}
	
}

